name: Notion2Github
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 14 * * *'
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github Frontend
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/frontend
          filter-prop: Main Category
          filter-value: Frontend
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Infra
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/infra
          filter-prop: Main Category
          filter-value: Infra
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Algorithm
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/algorithm
          filter-prop: Main Category
          filter-value: Algorithm
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Data
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/data
          filter-prop: Main Category
          filter-value: Data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md
          commit_message: 'docs: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: auto-sync-from-notion-to-github
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GH pages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_USER }}
      - run: |
          npm install
          npm run build
          npm run deploy
