name: Notion2Github
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 14 * * *'
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github Frontend
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/frontend
          filter-prop: Main Category
          filter-value: Frontend
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Infra
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/infra
          filter-prop: Main Category
          filter-value: Infra
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Algorithm
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/algorithm
          filter-prop: Main Category
          filter-value: Algorithm
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Notion2Github Data
        uses: younho9/notion2github@main
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          docs-directory: ./docs/data
          filter-prop: Main Category
          filter-value: Data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./docs/**/*.md
          commit_message: 'docs: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: auto-sync-from-notion-to-github
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
